openapi: 3.0.0
info:
  version: 0.1-oas3
  title: MLProject
  description: >-
    A simple service to facilitate the use of my E222 ML algorithm using swagger-3.0
    specification and codegen
  termsOfService: 'http://swagger.io/terms/'
  contact:
    name: Cloudmesh REST Service Example
  license:
    name: Apache
paths:
  /pred/<arg>:
    get:
      tags:
        - PREDICTION
      operationId: files.Model.MakePredict
      description: Returns a prediction about whether or not the patient with the given characteristics is likely to have had a stroke
      responses:
        '200':
          description: 'Prediction'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CPU'
    post:
      tags:
        - Upload
      summary: upload a CSV file for batch prediction processing
      operationId: files.Model.filePred
      responses:
        '405':
            description: Invalid input
  /tree:
      get:
        tags:
          - PREDICTION
        operationId: files.Model.getTree
        description: get tree 
        responses:
          '200':
            description: 'tree'
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/CPU'

servers:
  - url: 'http://localhost:8080'
components:
  schemas:
    CPU:
      type: object
      required:
        - model
      properties:
        model:
          type: string
